# PJC C03 by Rafał Pocztarski
# https://github.com/rsp/rsp-skj-p02
# https://gitlab.com/rsp/rsp-skj-p02

ALL = SumClient.class

all: $(ALL)

SumClient.class: *.java Makefile
	javac *.java

clean:
	$(RM) *.class

